FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends gcc libc6-dev && rm -rf /var/lib/apt/lists/*

COPY userbot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY userbot/ .

EXPOSE 8082

CMD ["python", "main.py"]
